### ISSUE TITLE
Option for opening folds if the last edited area is inside a closed fold

### ISSUE THREAD

**Issue by oblitum** [farmergreg/vim-lastplace#11]
I'd like to feature request an option for this feature of automatically opening folds, personally I don't like it because sometimes when opening a file one wants to check another position in the file and not care about the last one or the last fold, which sometimes one even wishes to keep closed because of that.

**Comment by farmergreg** [comment]
If i add a new setting, would it fix your problem? Pseudo code below:
- Add a variable called g:lastplace_open_folds
  - default: let g:lastplace_open_folds = 1
- when g:lastplace_open_folds == 0, jump to the last edit position. do not open folds.
- when g:lastplace_open_folds !=0, jump to the last edit position. open folds.

**Comment by oblitum** [comment]
Yes sure, sorry the late response. I think the current behaviour is not expected/wished for everyone. To tell the truth, I inferred it was vim-lastplace that was doing it without bisecting my plugins, I was about to ask why vim was doing that on vi.stackexchange.com. Maybe possibly, let folds closed, as it's vim default behaviour, should be the plugin's default behaviour too? With the user having to be explicit about wanting that.

Regardless of default behaviour, an option would would be fine.

**Comment by farmergreg** [comment]
@somini do you have any opinions on this?

I just pushed a change set that implements the pseudo code described above. It would be great if our "folds" people @oblitum  and @somini  tried it out :) Please post here after you've tried it so I know it's working.

Thanks!

**Comment by oblitum** [comment]
@dietsche thanks! This is good for me, already using it.

**Comment by somini** [comment]
Thanks for summoning me! I'm ok with putting this behind a flag, but I think the default should be opening the folds, otherwise the plugin might not seem to do anything. IMHO, if you don't want vim to goto the last place when you open a file, you can disable the plugin. 

I can try this code later today.

**Comment by farmergreg** [comment]
Thanks for the feedback! We'll leave the default as is (open the folds). I'll close this issue now. Feel free to re-open it if problems are found :)
