### ISSUE TITLE
doesn't play well with NERDTree and TagBar

### ISSUE THREAD

**Issue by LER0ever** [farmergreg/vim-lastplace#14]
Vim-Lastplace works well when opening a file using NERDTree, but if I toggle tagbar after opening the file, the entire layout get messed up.

I've found a [stackoverflow question (#33516037)](http://stackoverflow.com/questions/33516037/vim-nerdtree-tagbar-not-working-as-expected) that describes the exact situation and even have text diagram explaning the situation. It seems that **BufWinEnter** function causes this issue.

**Comment by farmergreg** [comment]
Thanks for the bug report. I'll take a closer look at this when I get some free time.

In the meantime, I'd like to confirm if this is a bug in vim-lastplace, or if it's a bug in NERDTree, TagBar, or vim.

As always, if it's a vim-lastplace bug and you have the time to create a fix, your help would be greatly appreciated.

Thanks!

**Comment by farmergreg** [comment]
@LER0ever I think I've fixed this bug in master. Please let me know if the fix is working for you.

Thanks!
