### ISSUE TITLE
vim-lastplace conflicts with vim-buffergator

### ISSUE THREAD

**Issue by r-learner** [farmergreg/vim-lastplace#16]
The recent commit conflicts with vim-buffergator. 
```
Error detected while processing function <SNR>38_lastplace:
line    2:
E16: Invalid range
E16: Invalid range
```
The conflict was introduced at the commit `f1c8989ea6af5ed297d7d622d190a86cc86f7681`, the commit `36c4ae38130232134ece7bdd0e844d8034b585ab` works.

Maybe I could change the default setting to ignore vim-buffergator list window, but I do not know vim-buffergator list window type or name.
```
    let g:lastplace_ignore = "gitcommit,gitrebase,svn,hgcommit"
    let g:lastplace_ignore_buftype = "quickfix,nofile,help"
```

**Comment by farmergreg** [comment]
Hi @r-learner thanks for the bug report! Can you give me detailed steps to reproduce this problem? I have the latest version of vim-buffergator installed and it is working for me when I use &lt;leader&gt;b to open the window that lists all open buffers.

**Comment by farmergreg** [comment]
@r-learner I was able to reproduce it on a system that is running an older vim than the one I originally tested on. Please let me know if this fix solves your problem. Thanks!

**Comment by r-learner** [comment]
Thank you very much.  The commit works well on neovim.
Btw, I am using neovim v0.2.0.
