### ISSUE TITLE
vim-lastplace can not work well with latest vim

### ISSUE THREAD

**Issue by cs-pchsu** [farmergreg/vim-lastplace#20]
I use vim-lastplace under some environment such as ubuntu14, lubuntu14, lubuntu18.

In the ubuntu14, lubuntu14, vim-lastplace work very well.
However, in the lubuntu18, vim-lastplace can not work well with latest vim.
The cursor is always on the first line, no matter which line was last opened

vim --version
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Apr 10 2018 21:31:58)
Included patches: 1-1453

lsb_release -d
Description:    Ubuntu 18.04 LTS

**Comment by farmergreg** [comment]
works fine for me.
