### ISSUE TITLE
let g:lastplace_open_folds = 0 still opens fold after reopening file

### ISSUE THREAD

**Issue by astier** [farmergreg/vim-lastplace#22]
Hi. Folds open after reopening a file even tho `let g:lastplace_open_folds = 0` is set.

0. Set `let g:lastplace_open_folds = 0` in your vimrc
1. Open file & create a paragraph
2. Fold paragraph with `zfip`
3. Exit vim and open it again
4. See that fold is now open

I use `nvim v0.4.3`

**Comment by farmergreg** [comment]
Hi, Thanks for the bug report!

I don't use folds a lot. Can you help me understand more about your setup? What foldmethod are you using? Anything else unique about your setup? Can you provide a sample document that I can fold some paragraphs with zfip? Also, how does vim behave if you temporarily remove vim-lastplace?

Thanks!

**Comment by astier** [comment]
Minimal vimrc:

```vim
cal plug#begin('~/.local/share/nvim/plugins')
Plug 'farmergreg/vim-lastplace'
cal plug#end()
let g:lastplace_open_folds = 0

" this
" is
" a
" paragraph
" fold
" me
```

Foldmethod should then be manual.
Without lastplace vim also opens the fold after reopening the file.
But this is expected behavior.

Or do I misunderstand the purpose of `lastplace_open_folds`?

**Comment by farmergreg** [comment]
It's behaving as expected. The g:lastplace_open_folds feature won't close any folds. It will only open them, when needed. 

vim-lastplace doesn't have any mechanism to save the view state which would include folds. If you'd like vim to remember what was folded, you might need to use mkview / loadview, or find a plugin that would manage that for you.

Thanks for your bug report! I'll close it for now. Please feel free to re-open it if you have any further questions or thoughts.

**Comment by astier** [comment]
Oh yeah sorry somehow. I missunderstood the docs. I was sleep deprived.

**Comment by farmergreg** [comment]
@astier happens to the best of us :)
