### ISSUE TITLE
Save lastplace_ignore and lastplace_ignore_buftype as list instead of string

### ISSUE THREAD

**Issue by astier** [farmergreg/vim-lastplace#26]
Hi. Just a minor thing I noticed in your code. You are storing `lastplace_ignore` and `lastplace_ignore_buftype` as strings instead of a list. If you would store them as a list you wouldn't need to call `split()` on them here:
https://github.com/farmergreg/vim-lastplace/blob/8f6c4454eb462776b6ebdc48e3e29a68ddeb726d/plugin/vim-lastplace.vim#L30

**Comment by farmergreg** [comment]
Hi @astier, it's too late to change this now because it would not be backwards compatible. thanks for your input!
