### ISSUE TITLE
`g:lastplace_open_folds` doesn't work when `foldmethod` is set in modeline

### ISSUE THREAD

**Issue by djpohly** [farmergreg/vim-lastplace#30]
Since the `BufRead` event happens before modelines are processed, lastplace cannot tell when the cursor will be inside a fold. It sounds from `:help BufRead` that `BufWinEnter` would be the right place for this functionality.

**Comment by farmergreg** [comment]
@djpohly could you test and see if this bug has been fixed? i don't use folds very much, but i think i've found and fixed the issue you found. Thanks for the bug report and your help!
