### ISSUE TITLE
Error Message:"Need to specify how to reconcile divergent branch"

### ISSUE THREAD

**Issue by Damianus500** [farmergreg/vim-lastplace#32]
I am running vim on popos 22 (linux).

I have been using lastplace plugin for years without issue. 

BUT today ... I received the following ERROR message while doing a PluginUpdate

![image](https://github.com/farmergreg/vim-lastplace/assets/83386270/d6e55c79-d48a-42d8-9536-ec3e571c9840)

Sorry I don't know how to follow the hint "git config --global"

Any help much appreciated.

 DL
 
 
 ---

My VIM version:

VIM - Vi IMproved 9.0 (2022 Jun 28, compiled May 10 2022 08:40:37)
Included patches: 1-749
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               +file_in_path      +mouse_urxvt       -tag_any_white
+arabic            +find_in_path      +mouse_xterm       +tcl
+autocmd           +float             +multi_byte        +termguicolors
+autochdir         +folding           +multi_lang        +terminal
-autoservername    -footer            -mzscheme          +terminfo
+balloon_eval      +fork()            +netbeans_intg     +termresponse
+balloon_eval_term +gettext           +num64             +textobjects
+browse            -hangul_input      +packages          +textprop
++builtin_terms    +iconv             +path_extra        +timers
+byte_offset       +insert_expand     +perl              +title
+channel           +ipv6              +persistent_undo   +toolbar
+cindent           +job               +popupwin          +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +vim9script
+cmdline_hist      +langmap           -python            +viminfo
+cmdline_info      +libcall           +python3           +virtualedit
+comments          +linebreak         +quickfix          +visual
+conceal           +lispindent        +reltime           +visualextra
+cryptv            +listcmds          +rightleft         +vreplace
+cscope            +localmap          +ruby              +wildignore
+cursorbind        +lua               +scrollbind        +wildmenu
+cursorshape       +menu              +signs             +windows
+dialog_con_gui    +mksession         +smartindent       +writebackup
+diff              +modify_fname      +sodium            +X11
+digraphs          +mouse             +sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary
-farsi             -mouse_sysmouse    -tag_old_static
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng16 -I/usr/include/x86_64-linux-gnu -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time -g -O2 -ffile-prefix-map=/build/vim-cdpF6P/vim-9.0.0749=. -flto=auto -ffat-lto-objects -flto=auto -ffat-lto-objects -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1
Linking: gcc -L. -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,-E -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE -lm -ltinfo -lselinux -lcanberra -lsodium -lacl -lattr -lgpm -L/usr/lib -llua5.2 -Wl,-E -fstack-protector-strong -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu/perl/5.34/CORE -lperl -ldl -lm -lpthread -lcrypt -L/usr/lib/python3.10/config-3.10-x86_64-linux-gnu -lpython3.10 -lcrypt -ldl -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm -lruby-3.0 -lm -L/usr/lib

**Comment by farmergreg** [comment]
Hi @Damianus500 , this is happening because of a mistake I made. I accidentally forced pushed to this repository a few weeks ago, and then undid the change hoping that no one pulled while the bad branch was still up. Sorry for the trouble! I'm not super familiar with git submodules, so I can't give any specific guidance there. However, if you can set the submodule so that master points at 48ba343c8c1ca3039224727096aae214f51327d1 (the previous release commit) and then update, I think things will work. I'll try to replicate your problem tomorrow and see what I can figure out.

**Comment by Damianus500** [comment]
Hi Greg:

Chill. No problem 😄. I can wait for you to put things right. No hurry.

THANK you for the plug-in. Appreciate your effort!

DL

**Comment by farmergreg** [comment]
Hi @Damianus500,
This is untested, but in the sub-module folder for vim-lastplace, I think you can run:

```
git submodule deinit -f .
git submodule update --init
```

This idea comes from:
https://stackoverflow.com/questions/10906554/how-do-i-revert-my-changes-to-a-git-submodule

**Comment by Damianus500** [comment]
I execute the above commands (without the '.' at the end of first command, I think it's an error, right?) in my vim-lastplace folder.

⚝ Wed Sep 27  21:45 靜 ᗫ ⚝  ↬ git submodule deinit -f
fatal: Use '--all' if you really want to deinitialize all submodules
~/.vim/bundle/vim-lastplace •
⚝ Wed Sep 27  21:45 靜 ᗫ ⚝  ↬ git submodule update --init⚝ Wed Sep 27  21:45 靜 ᗫ ⚝  ↬ git submodule deinit -f
fatal: Use '--all' if you really want to deinitialize all submodules
~/.vim/bundle/vim-lastplace •
⚝ Wed Sep 27  21:45 靜 ᗫ ⚝  ↬ git submodule update --init

Afterwards, I start vim and execute 'PluginUpdate'

I still get the same error as before. No joy.

DL

**Comment by natecraddock** [comment]
A possible solution is to just uninstall and reinstall the plugin right? I don't believe vim-lastplace has any user settings stored in the plugin directory. So if your plugin manager has a way to uninstall a plugin you could try that. Or just remove the vim-lastplace directory manually. Either way, once it is gone I expect you can reinstall the plugin using your plugin manager.

**Comment by Damianus500** [comment]
natecraddock is correct. I did just that and problem disappeared.

The KISS principle works ... KEEP IT SIMPLE STUPID!

Thank you Natecraddock & farmerGregory!

DL

**Comment by natecraddock** [comment]
Yeah there definitely was some way to fix the git state, but as you say sometimes the simple solution is the best. Glad to help!
