### ISSUE TITLE
Compare to vim-stay

### ISSUE THREAD

**Issue by Konfekt** [farmergreg/vim-lastplace#7]
Useful plugin, and new to me. Interesting would be a comparison, or even symbiosis, with  https://github.com/kopischke/vim-stay which, on first glance, does something similar.

**Comment by farmergreg** [comment]
Please submit a patch. Thanks!

**Comment by Konfekt** [comment]
Hmm.. you know vim-lastplace better than the greenhorn over here. It seems to me that `vim-stay` restores folds and other information as well, whereas `vim-lastplace` focuses on restoring the cursor position and unfolding to see it, whenever necessary. It was more meant as a hint than a pull request of mine that blends them together.

**Comment by farmergreg** [comment]
Thanks, @Konfekt
